// Config Components - CRUD completo
export { AtributosConfigComponent } from './atributos-config.component';
export { AptidoesConfigComponent } from './aptidoes-config.component';
export { NiveisConfigComponent } from './niveis-config.component';
export { LimitadoresConfigComponent } from './limitadores-config.component';
export { ClassesConfigComponent } from './classes-config.component';
export { VantagensConfigComponent } from './vantagens-config.component';
export { RacasConfigComponent } from './racas-config.component';
export { ProspeccaoConfigComponent } from './prospeccao-config.component';
export { PresencasConfigComponent } from './presencas-config.component';
export { GenerosConfigComponent } from './generos-config.component';
